### PR TITLE
Improved the controls by making the player move in the direction he is facing.

### PR DESCRIPTION
**Pull request by AidanLovelace**

### CODE REVIEW

**Comment by Hazurl** [comment]
It feels really weird... When we are moving the mouse fast and everywhere, it become really hard to control the character...
And btw, `TransformComponent` has a method called `front` and `right` so you don't need to calcul that.

**Comment by AidanLovelace** [comment]
Okay. I'm not a huge fan of how `w` is always `north`. It feels very weird. What if we make the camera rotate with the player and have w always be forward. Or, maybe we could have the little guy only move along axies like in older top down games.

**Comment by Jackojc** [comment]
Maybe add it as an optional thing?

**Comment by HumbleDeer** [comment]
an optional thing would be fine, I think.

**Pull request closed without merging**
